@startuml

abstract class ActionBase {
    {abstract} {method} rangeAndCosts() // tiles that may be affected by this action with costs
    
}

class ActionGlobal{
}

class ActionUnit{
}

class ActionTile{
}



interface Autonomous {
}


ActionBase <|-- ActionGlobal
ActionBase <|-- ActionTile
ActionBase <|-- ActionUnit

Autonomous <|-- ActionBase

class ActionUnitFieldOfView {
}

Autonomous <|.. ActionUnitFieldOfView
ActionUnit <|-- ActionUnitFieldOfView

@enduml