@startuml



abstract class PlaygroundView {  }


abstract class Renderer {
  view: PlaygroundView|undefined;
  renderablesFactory: RenderablesFactory|undefined;
  {method} setView(view: PlaygroundView):void
  {method} setRenderablesFactory(factory: RenderablesFactory):void
}

abstract class HudRenderer {
  components: HudComponent[];
  {method} addComponent(component:HudComponent):void;
  {method} repositionComponents():void;
}

abstract class HudRendererThreeJs {}

abstract class MapRenderer {
  {field} width: number;
  {field} height: number;
  {field} assets: string;

  {method} initialize():Promise<void>;
  {method} remove(tile: TileBase):void;
  {method} replace(tile: TileBase, direction:string):void;
  {method} put(tile: TileBase, direction:string):void;
  {method} onTileChanged(tile: TileBase, direction: string):void;
  {method} xyToScenePosition(y: number, x:number):ScenePosition;
}

abstract class MapRendererThreeJs {
  tileSize: number;
  mapHolderObject: THREE.Object3D;
  tileFactory: RenderableThreeJSObject3DFactory;

  {method} _dispose(object3D:THREE.Mesh)
}

class MapQuadRendererThreeJs {
  {method} _directionRotate(object3D:THREE.Object3D, direction:string)
}

abstract class RenderablesFactory {
  {method} spawnRenderableObject(objectName:string):Renderable;
  {method} loadRenderablesObjectsTemplate(path:string):Promise<void>;
}

class RenderablesThreeJSFactory {
  templates:Map<string, THREE.Object3D>;
  loader: any;
  {method} _matchingChildren(children:any[], filterNames: string[]):any[]
  {method} _cloneMaterials(parent:THREE.Mesh)
  {method} _addTemplate(name:string, object3D:THREE.Object3D)
}

interface Renderable{
  name: string,
  data: any
}

interface RenderableThreeJS {
  data: THREE.Object3D
}

interface ScenePosition {
  x: number,
  y: number,
  z: number
}

PlaygroundView <.. Renderer : renders/draws Renderables on target view

Renderer <|-- MapRenderer
Renderer <|-- HudRenderer
HudRenderer <|-- HudRendererThreeJs
MapRenderer <|-- MapRendererThreeJs
MapRendererThreeJs <|-- MapQuadRendererThreeJs
Renderer .. RenderablesFactory
RenderablesFactory .. Renderable

RenderablesFactory <|.. RenderablesThreeJSFactory

Renderable <|-- RenderableThreeJS
@enduml