@startuml

abstract class UnitBase {    
  {field} string uid  // unit unique id
  {field} number hitPoints  // when 0 unit is dead
  {field} number actionPoints // what unit can do
  {field} UnitSpecs unitSpecification // what unit can do
}

interface Actionable {
  {field} ActionBase[] actionsAllowed 
  {field} ActionBase[] actionsAll
  {field} ActionBase[] actionsQueue // planned actions for entity
  {field} ActionRunner actionRunner // currently processing long lasting action  
}

Actionable <|-- UnitBase

abstract class UnitSpecs {     
  {field} string tuid // unit specification unique id, type id 
}

UnitBase .. UnitSpecs : unit specification


@enduml